export const Sport = [
	["Accrobranche"], ["Accrobranche"],
	["Acrosport"], ["Acrosport"],
	["Aérobic"], ["Aerobic"],
	["Aéromodélisme"], ["Aeromodelisme"],
	["Aérostation"], ["Aerostation"],
	["Agility"], ["Agility"],
	["Aïkido"], ["Aikido"],
	["Airsoft"], ["Airsoft"],
	["Alpinisme"], ["Alpinisme"],
	["Aquabiking"], ["Aquabiking"],
	["Aquagym"], ["Aquagym"],
	["Aquajogging"], ["Aquajogging"],
	["Aquarunning"], ["Aquarunning"],
	["Aquathlon"], ["Aquathlon"],
	["Aquatriathlon"], ["Aquatriathlon"],
	["Athlétisme"], ["Athletisme"],
	["Automobile"], ["Automobile"],
	["Aviation"], ["Aviation"],
	["Aviron"], ["Aviron"],
	["Baby-foot"], ["Baby-Foot"],
	["Badminton"], ["Badminton"],
	["Base-jump"], ["Base-Jump"],
	["Baseball"], ["Baseball"],
	["Basket-ball"], ["Basket-Ball"],
	["Bateau-Dragon"], ["Bateau-Dragon"],
	["Biathlon"], ["Biathlon"],
	["Billard"], ["Billard"],
	["Bloc (escalade)"], ["Bloc(Escalade)"],
	["BMX"], ["Bmx"],
	["Boardercross"], ["Boardercross"],
	["Bobsleigh"], ["Bobsleigh"],
	["Boccia"], ["Boccia"],
	["Bodyboard"], ["Bodyboard"],
	["Boomerang"], ["Boomerang"],
	["Boule lyonnaise"], ["BouleLyonnaise"],
	["Bowling"], ["Bowling"],
	["boxe thaïlandaise"], ["BoxeThailandaise"],
	["Bras de fer"], ["BrasDeFer"],
	["Canicross"], ["Canicross"],
	["Canoë"], ["Canoe"],
	["Canoë-kayak"], ["Canoe-Kayak"],
	["Canyoning"], ["Canyoning"],
	["Capoeira"], ["Capoeira"],
	["Carrom"], ["Carrom"],
	["Catamaran"], ["Catamaran"],
	["Catch"], ["Catch"],
	["Cheerleading"], ["Cheerleading"],
	["Coasteering"], ["Coasteering"],
	["Combat"], ["Combat"],
	["Compétition automobile"], ["CompetitionAutomobile"],
	["Course à pied"], ["CourseAPied"],
	["Course camarguaise"], ["CourseCamarguaise"],
	["Course d'orientation"], ["CourseD'Orientation"],
	["Cricket"], ["Cricket"],
	["Croquet"], ["Croquet"],
	["Cross (équitation)"], ["Cross(Equitation)"],
	["Cross-country"], ["Cross-Country"],
	["Cross triathlon"], ["CrossTriathlon"],
	["Crosse"], ["Crosse"],
	["CrossFit"], ["Crossfit"],
	["Culturisme"], ["Culturisme"],
	["Curling"], ["Curling"],
	["Cyclisme"], ["Cyclisme"],
	["Danse sportive"], ["DanseSportive"],
	["Dames"], ["Dames"],
	["Décathlon"], ["Decathlon"],
	["Deltaplane"], ["Deltaplane"],
	["Duathlon"], ["Duathlon"],
	["Dodgeball"], ["Dodgeball"],
	["Double Dutch"], ["DoubleDutch"],
	["Drift"], ["Drift"],
	["Échecs"], ["Echecs"],
	["Équitation"], ["Equitation"],
	["Escalade"], ["Escalade"],
	["Escrime"], ["Escrime"],
	["Formule 1"], ["Formule1"],
	["Floorball"], ["Floorball"],
	["Folkrace"], ["Folkrace"],
	["Football"], ["Football"],
	["Football américain"], ["FootballAmericain"],
	["Football australien"], ["FootballAustralien"],
	["Football gaélique"], ["FootballGaelique"],
	["Footing"], ["Footing"],
	["Glisse"], ["Glisse"],
	["Golf"], ["Golf"],
	["Gouren"], ["Gouren"],
	["Grappling"], ["Grappling"],
	["Gymnastique"], ["Gymnastique"],
	["Haka pei"], ["HakaPei"],
	["Hakko-Ryu"], ["Hakko-Ryu"],
	["Haltérophilie"], ["Halterophilie"],
	["Handball"], ["Handball"],
	["Hockey"], ["Hockey"],
	["Hockey subaquatique"], ["HockeySubaquatique"],
	["Hockey sur gazon"], ["HockeySurGazon"],
	["Hockey sur glace"], ["HockeySurGlace"],
	["Horse-ball"], ["Horse-Ball"],
	["Hurling"], ["Hurling"],
	["Jeu de paume"], ["JeuDePaume"],
	["Ju-Jitsu"], ["Ju-Jitsu"],
	["Joutes nautiques"], ["JoutesNautiques"],
	["Judo"], ["Judo"],
	["Javelot tir sur cible"], ["JavelotTirSurCible"],
	["Jiu-jitsu brésilien"], ["Jiu-JitsuBresilien"],
	["Jet ski"], ["JetSki"],
	["Kabaddi"], ["Kabaddi"],
	["Kaninhop"], ["Kaninhop"],
	["Karaté"], ["Karate"],
	["Karting"], ["Karting"],
	["Kayak"], ["Kayak"],
	["Kempo"], ["Kempo"],
	["Kendo"], ["Kendo"],
	["Kenjutsu"], ["Kenjutsu"],
	["Kickball"], ["Kickball"],
	["Kick-boxing japonais"], ["Kick-BoxingJaponais"],
	["Kitesurfing"], ["Kitesurfing"],
	["Kin-ball"], ["Kin-Ball"],
	["Kobudo"], ["Kobudo"],
	["Kung fu"], ["KungFu"],
	["Krav maga"], ["KravMaga"],
	["Kronum"], ["Kronum"],
	["Lancer de disque"], ["LancerDeDisque"],
	["Lancer de javelot"], ["LancerDeJavelot"],
	["Lancer de marteau"], ["LancerDeMarteau"],
	["Lancer de poids"], ["LancerDePoids"],
	["Luge de course"], ["LugeDeCourse"],
	["Marche"], ["Marche"],
	["Marche nordique"], ["MarcheNordique"],
	["Monocycle"], ["Monocycle"],
	["Motomarine"], ["Motomarine"],
	["Motoneige (sentier)"], ["Motoneige(Sentier)"],
	["Motoneige (hors piste)"], ["Motoneige(HorsPiste)"],
	["Moto (vitesse)"], ["Moto(Vitesse)"],
	["Moto (endurance)"], ["Moto(Endurance)"],
	["Moto (cross)"], ["Moto(Cross)"],
	["Moto (trial)"], ["Moto(Trial)"],
	["Moto (enduro)"], ["Moto(Enduro)"],
	["Musculation"], ["Musculation"],
	["Marathon"], ["Marathon"],
	["Naban"], ["Naban"],
	["Natation"], ["Natation"],
	["Natation synchronisée"], ["NatationSynchronisee"],
	["Nautisme"], ["Nautisme"],
	["Omnikin"], ["Omnikin"],
	["Paddle"], ["Paddle"],
	["Padel"], ["Padel"],
	["Paintball"], ["Paintball"],
	["Parachutisme"], ["Parachutisme"],
	["Parapente"], ["Parapente"],
	["Parkour"], ["Parkour"],
	["Patin à glace"], ["PatinAGlace"],
	["Patinage"], ["Patinage"],
	["Patinage artistique"], ["PatinageArtistique"],
	["Patinage de vitesse"], ["PatinageDeVitesse"],
	["Patinage synchronisé"], ["PatinageSynchronise"],
	["Pêche sportive"], ["PecheSportive"],
	["Pelote basque"], ["PeloteBasque"],
	["Pentathlon moderne"], ["PentathlonModerne"],
	["Pétanque"], ["Petanque"],
	["Pilates"], ["Pilates"],
	["Ping-Pong"], ["Ping-Pong"],
	["Planche à voile"], ["PlancheAVoile"],
	["Planeur (ou vol à voile)"], ["Planeur(OuVolAVoile)"],
	["Plongée en apnée"], ["PlongeeEnApnee"],
	["Plongée"], ["Plongee"],
	["Plongée sportive en piscine"], ["PlongeeSportiveEnPiscine"],
	["Plongeon"], ["Plongeon"],
	["Plumfoot"], ["Plumfoot"],
	["Qi gong"], ["QiGong"],
	["Quad"], ["Quad"],
	["Quidditch"], ["Quidditch"],
	["Rafting"], ["Rafting"],
	["Rallye automobile"], ["RallyeAutomobile"],
	["Raquette à neige"], ["RaquetteANeige"],
	["Régate"], ["Regate"],
	["Ringuette"], ["Ringuette"],
	["Rink hockey"], ["RinkHockey"],
	["Roller"], ["Roller"],
	["Roller in line hockey"], ["RollerInLineHockey"],
	["Rugby à sept"], ["RugbyASept"],
	["Rugby à XIII"], ["RugbyAXiii"],
	["Rugby à XV"], ["RugbyAXv"],
	["Roller derby"], ["RollerDerby"],
	["Sambo"], ["Sambo"],
	["Salsa"], ["Salsa"],
	["Savate (boxe française)"], ["Savate(BoxeFrancaise)"],
	["Saut à la perche"], ["SautALaPerche"],
	["Saut à ski"], ["SautASki"],
	["Saut en hauteur"], ["SautEnHauteur"],
	["Saut en longueur"], ["SautEnLongueur"],
	["Shinty"], ["Shinty"],
	["Skateboard"], ["Skateboard"],
	["Skater hockey"], ["SkaterHockey"],
	["Skeleton"], ["Skeleton"],
	["Ski"], ["Ski"],
	["Ski alpin"], ["SkiAlpin"],
	["Ski de fond"], ["SkiDeFond"],
	["Ski nordique"], ["SkiNordique"],
	["Ski nautique"], ["SkiNautique"],
	["Slamball"], ["Slamball"],
	["Snorkeling"], ["Snorkeling"],
	["Snowboard"], ["Snowboard"],
	["Snowscoot"], ["Snowscoot"],
	["Snowskate"], ["Snowskate"],
	["Softball"], ["Softball"],
	["Spéléologie"], ["Speleologie"],
	["Squash"], ["Squash"],
	["Step"], ["Step"],
	["Sumo"], ["Sumo"],
	["Supermotard"], ["Supermotard"],
	["Tae Bo"], ["TaeBo"],
	["Taekwondo"], ["Taekwondo"],
	["Tai-chi-chuan"], ["Tai-Chi-Chuan"],
	["Taihojutsu"], ["Taihojutsu"],
	["Taïso"], ["Taiso"],
	["Tambourin"], ["Tambourin"],
	["Tango"], ["Tango"],
	["Tau'a rapa nui"], ["Tau'ARapaNui"],
	["Tchoukball"], ["Tchoukball"],
	["Tennis"], ["Tennis"],
	["Tennis de table"], ["TennisDeTable"],
	["Tennis léger"], ["TennisLeger"],
	["Tir à l'arc"], ["TirAL'Arc"],
	["Tir sportif"], ["TirSportif"],
	["Trampoline"], ["Trampoline"],
	["Triathlon"], ["Triathlon"],
	["Tricking"], ["Tricking"],
	["Triple saut"], ["TripleSaut"],
	["Trottinette freestyle"], ["TrottinetteFreestyle"],
	["ULM"], ["Ulm"],
	["Ultimate"], ["Ultimate"],
	["Varappe"], ["Varappe"],
	["Vélocross (vélo cross-country, VTT)"], ["Velocross(VeloCross-Country,Vtt)"],
	["Voile"], ["Voile"],
	["Volata"], ["Volata"],
	["Volley-ball"], ["Volley-Ball"],
	["Voltige aérienne"], ["VoltigeAerienne"],
	["Wakeboard"], ["Wakeboard"],
	["Water-polo"], ["Water-Polo"],
	["Wing chun"], ["WingChun"],
	["Yoga"], ["Yoga"],
	["Zen Hakko Kaï"], ["ZenHakkoKai"],
];