export const SportList: string[][] = [
	["Accrobranche", "Accrobranche"],
	["Acrosport", "Acrosport"],
	["Aérobic", "Aérobic"],
	["Aéromodélisme", "Aéromodélisme"],
	["Aérostation", "Aérostation"],
	["Agility", "Agility"],
	["Aïkido", "Aïkido"],
	["Airsoft", "Airsoft"],
	["Alpinisme", "Alpinisme"],
	["Aquabiking", "Aquabiking"],
	["Aquagym", "Aquagym"],
	["Aquajogging", "Aquajogging"],
	["Aquarunning", "Aquarunning"],
	["Aquathlon", "Aquathlon"],
	["Aquatriathlon", "Aquatriathlon"],
	["Athlétisme", "Athlétisme"],
	["Automobile", "Automobile"],
	["Aviation", "Aviation"],
	["Aviron", "Aviron"],
	["Baby-foot", "Baby-foot"],
	["Badminton", "Badminton"],
	["Base-jump", "Base-jump"],
	["Baseball", "Baseball"],
	["Basket-ball", "Basket-ball"],
	["Bateau-Dragon", "Bateau-Dragon"],
	["Biathlon", "Biathlon"],
	["Billard", "Billard"],
	["Bloc (escalade)", "Bloc (escalade)"],
	["BMX", "BMX"],
	["Boardercross", "Boardercross"],
	["Bobsleigh", "Bobsleigh"],
	["Boccia", "Boccia"],
	["Bodyboard", "Bodyboard"],
	["Boomerang", "Boomerang"],
	["Boule lyonnaise", "Boule lyonnaise"],
	["Bowling", "Bowling"],
	["boxe thaïlandaise", "boxe thaïlandaise"],
	["Bras de fer", "Bras de fer"],
	["Canicross", "Canicross"],
	["Canoë", "Canoë"],
	["Canoë-kayak", "Canoë-kayak"],
	["Canyoning", "Canyoning"],
	["Capoeira", "Capoeira"],
	["Carrom", "Carrom"],
	["Catamaran", "Catamaran"],
	["Catch", "Catch"],
	["Cheerleading", "Cheerleading"],
	["Coasteering", "Coasteering"],
	["Combat", "Combat"],
	["Compétition automobile", "Compétition automobile"],
	["Course à pied", "Course à pied"],
	["Course camarguaise", "Course camarguaise"],
	["Course d'orientation", "Course d'orientation"],
	["Cricket", "Cricket"],
	["Croquet", "Croquet"],
	["Cross (équitation)", "Cross (équitation)"],
	["Cross-country", "Cross-country"],
	["Cross triathlon", "Cross triathlon"],
	["Crosse", "Crosse"],
	["CrossFit", "CrossFit"],
	["Culturisme", "Culturisme"],
	["Curling", "Curling"],
	["Cyclisme", "Cyclisme"],
	["Danse sportive", "Danse sportive"],
	["Dames", "Dames"],
	["Décathlon", "Décathlon"],
	["Deltaplane", "Deltaplane"],
	["Duathlon", "Duathlon"],
	["Dodgeball", "Dodgeball"],
	["Double Dutch", "Double Dutch"],
	["Drift", "Drift"],
	["Échecs", "Échecs"],
	["Équitation", "Équitation"],
	["Escalade", "Escalade"],
	["Escrime", "Escrime"],
	["Formule 1", "Formule 1"],
	["Floorball", "Floorball"],
	["Folkrace", "Folkrace"],
	["Football", "Football"],
	["Football américain", "Football américain"],
	["Football australien", "Football australien"],
	["Football gaélique", "Football gaélique"],
	["Footing", "Footing"],
	["Glisse", "Glisse"],
	["Golf", "Golf"],
	["Gouren", "Gouren"],
	["Grappling", "Grappling"],
	["Gymnastique", "Gymnastique"],
	["Haka pei", "Haka pei"],
	["Hakko-Ryu", "Hakko-Ryu"],
	["Haltérophilie", "Haltérophilie"],
	["Handball", "Handball"],
	["Hockey", "Hockey"],
	["Hockey subaquatique", "Hockey subaquatique"],
	["Hockey sur gazon", "Hockey sur gazon"],
	["Hockey sur glace", "Hockey sur glace"],
	["Horse-ball", "Horse-ball"],
	["Hurling", "Hurling"],
	["Jeu de paume", "Jeu de paume"],
	["Ju-Jitsu", "Ju-Jitsu"],
	["Joutes nautiques", "Joutes nautiques"],
	["Judo", "Judo"],
	["Javelot tir sur cible", "Javelot tir sur cible"],
	["Jiu-jitsu brésilien", "Jiu-jitsu brésilien"],
	["Jet ski", "Jet ski"],
	["Kabaddi", "Kabaddi"],
	["Kaninhop", "Kaninhop"],
	["Karaté", "Karaté"],
	["Karting", "Karting"],
	["Kayak", "Kayak"],
	["Kempo", "Kempo"],
	["Kendo", "Kendo"],
	["Kenjutsu", "Kenjutsu"],
	["Kickball", "Kickball"],
	["Kick-boxing japonais", "Kick-boxing japonais"],
	["Kitesurfing", "Kitesurfing"],
	["Kin-ball", "Kin-ball"],
	["Kobudo", "Kobudo"],
	["Kung fu", "Kung fu"],
	["Krav maga", "Krav maga"],
	["Kronum", "Kronum"],
	["Lancer de disque", "Lancer de disque"],
	["Lancer de javelot", "Lancer de javelot"],
	["Lancer de marteau", "Lancer de marteau"],
	["Lancer de poids", "Lancer de poids"],
	["Luge de course", "Luge de course"],
	["Marche", "Marche"],
	["Marche nordique", "Marche nordique"],
	["Monocycle", "Monocycle"],
	["Motomarine", "Motomarine"],
	["Motoneige (sentier)", "Motoneige (sentier)"],
	["Motoneige (hors piste)", "Motoneige (hors piste)"],
	["Moto (vitesse)", "Moto (vitesse)"],
	["Moto (endurance)", "Moto (endurance)"],
	["Moto (cross)", "Moto (cross)"],
	["Moto (trial)", "Moto (trial)"],
	["Moto (enduro)", "Moto (enduro)"],
	["Musculation", "Musculation"],
	["Marathon", "Marathon"],
	["Naban", "Naban"],
	["Natation", "Natation"],
	["Natation synchronisée", "Natation synchronisée"],
	["Nautisme", "Nautisme"],
	["Omnikin", "Omnikin"],
	["Paddle", "Paddle"],
	["Padel", "Padel"],
	["Paintball", "Paintball"],
	["Parachutisme", "Parachutisme"],
	["Parapente", "Parapente"],
	["Parkour", "Parkour"],
	["Patin à glace", "Patin à glace"],
	["Patinage", "Patinage"],
	["Patinage artistique", "Patinage artistique"],
	["Patinage de vitesse", "Patinage de vitesse"],
	["Patinage synchronisé", "Patinage synchronisé"],
	["Pêche sportive", "Pêche sportive"],
	["Pelote basque", "Pelote basque"],
	["Pentathlon moderne", "Pentathlon moderne"],
	["Pétanque", "Pétanque"],
	["Pilates", "Pilates"],
	["Ping-Pong", "Ping-Pong"],
	["Planche à voile", "Planche à voile"],
	["Planeur (ou vol à voile)", "Planeur (ou vol à voile)"],
	["Plongée en apnée", "Plongée en apnée"],
	["Plongée", "Plongée"],
	["Plongée sportive en piscine", "Plongée sportive en piscine"],
	["Plongeon", "Plongeon"],
	["Plumfoot", "Plumfoot"],
	["Qi gong", "Qi gong"],
	["Quad", "Quad"],
	["Quidditch", "Quidditch"],
	["Rafting", "Rafting"],
	["Rallye automobile", "Rallye automobile"],
	["Raquette à neige", "Raquette à neige"],
	["Régate", "Régate"],
	["Ringuette", "Ringuette"],
	["Rink hockey", "Rink hockey"],
	["Roller", "Roller"],
	["Roller in line hockey", "Roller in line hockey"],
	["Rugby à sept", "Rugby à sept"],
	["Rugby à XIII", "Rugby à XIII"],
	["Rugby à XV", "Rugby à XV"],
	["Roller derby", "Roller derby"],
	["Sambo", "Sambo"],
	["Salsa", "Salsa"],
	["Savate (boxe française)", "Savate (boxe française)"],
	["Saut à la perche", "Saut à la perche"],
	["Saut à ski", "Saut à ski"],
	["Saut en hauteur", "Saut en hauteur"],
	["Saut en longueur", "Saut en longueur"],
	["Shinty", "Shinty"],
	["Skateboard", "Skateboard"],
	["Skater hockey", "Skater hockey"],
	["Skeleton", "Skeleton"],
	["Ski", "Ski"],
	["Ski alpin", "Ski alpin"],
	["Ski de fond", "Ski de fond"],
	["Ski nordique", "Ski nordique"],
	["Ski nautique", "Ski nautique"],
	["Slamball", "Slamball"],
	["Snorkeling", "Snorkeling"],
	["Snowboard", "Snowboard"],
	["Snowscoot", "Snowscoot"],
	["Snowskate", "Snowskate"],
	["Softball", "Softball"],
	["Spéléologie", "Spéléologie"],
	["Squash", "Squash"],
	["Step", "Step"],
	["Sumo", "Sumo"],
	["Supermotard", "Supermotard"],
	["Tae Bo", "Tae Bo"],
	["Taekwondo", "Taekwondo"],
	["Tai-chi-chuan", "Tai-chi-chuan"],
	["Taihojutsu", "Taihojutsu"],
	["Taïso", "Taïso"],
	["Tambourin", "Tambourin"],
	["Tango", "Tango"],
	["Tau'a rapa nui", "Tau'a rapa nui"],
	["Tchoukball", "Tchoukball"],
	["Tennis", "Tennis"],
	["Tennis de table", "Tennis de table"],
	["Tennis léger", "Tennis léger"],
	["Tir à l'arc", "Tir à l'arc"],
	["Tir sportif", "Tir sportif"],
	["Trampoline", "Trampoline"],
	["Triathlon", "Triathlon"],
	["Tricking", "Tricking"],
	["Triple saut", "Triple saut"],
	["Trottinette freestyle", "Trottinette freestyle"],
	["ULM", "ULM"],
	["Ultimate", "Ultimate"],
	["Varappe", "Varappe"],
	["Vélocross (vélo cross-country, VTT)", "Vélocross (vélo cross-country, VTT)"],
	["Voile", "Voile"],
	["Volata", "Volata"],
	["Volley-ball", "Volley-ball"],
	["Voltige aérienne", "Voltige aérienne"],
	["Wakeboard", "Wakeboard"],
	["Water-polo", "Water-polo"],
	["Wing chun", "Wing chun"],
	["Yoga", "Yoga"],
	["Zen Hakko Kaï", "Zen Hakko Kaï"],
];